version: '3.9'

services:
  at-api-v1.0.0:
    build:
      context: .
      dockerfile: Dockerfile
    image: at-api-v1.0.0-img
    container_name: at-api-v1.0.0
    working_dir: /app
    # command: npm ci --verbose
    # command: ls
    tty: true
    stdin_open: true
    volumes: 
      - .:/app
      #exclude
      - /app/node_modules